name: Python Code Quality
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: psf/black@stable
  check:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m pip install -r python/requirements-dev.txt
      - run: isort --check-only --diff .
